= Hybrid Cloud

== Download Sources

[source,bash]
----
git clone https://github.com/redhat-developer-demos/hybrid-cloud
export HYBRID_CLOUD_HOME=`pwd`/hybrid-cloud
git clone https://github.com/redhat-developer-demos/hybrid-cloud-app-frontend
export BACKEND_APP_HOME=`pwd`/hybrid-cloud-app-backend
git clone https://github.com/redhat-developer-demos/hybrid-cloud-app-backend
export FRONTEND_APP_HOME=`pwd`/hybrid-cloud-app-frontend
----

Lets use the following variables to refer to the source repositories cloned above:

- *$HYBRID_CLOUD_HOME* -- https://github.com/redhat-developer-demos/hybrid-cloud
- *$BACKEND_APP_HOME* -- https://github.com/redhat-developer-demos/hybrid-cloud-app-backend
- *$FRONTEND_APP_HOME* -- https://github.com/redhat-developer-demos/hybrid-cloud-app-frontend


== Prerequisites

* Three https://try.openshift.com[OpenShift4] cluster with following components installed:
** https://www.openshift.com/learn/topics/serverless[OpenShift Serverless]

* https://skupper.io/releases/index.html[skupper]

Let us call the OpenShift Clusters as *Cloud-1*, *Cloud-2* and *Cloud-3*.

The following table shows the cloud and what components gets installed on each of them:

.Clouds and Components
[cols="<2,^1,^1,^1", options="header"]
|===
| Component | Cloud-1  |  Cloud-2 | Cloud-3
| Cloud Provider  | gcp  |  aws | azr
| Backend   | &#x2713;  | &#x2713;  | &#x2713;
| Frontend  | &#x2713;  | &#x274C; | &#x274C;
| Generate Site Token(`token.yaml`)  | &#x2713;  | &#x274C; | &#x274C;
|===

NOTE: You can use any cloud provider for any OpenShift4 supported cloud, the gcp/aws/azr is used in this example.

Before the `backend` or `frontend` applications are deployed, execute the following on *each cloud*:

[source,bash]
----
cd $HYBRID_CLOUD_HOME
oc apply -k k8s/core
oc project hybrid-cloud-demo
oc apply -k k8s/rbac
----

=== Cloud-1(gcp)

=== Add Image Streams

[source,bash]
----
oc import-image hybrid-cloud-backend --confirm --all --from quay.io/rhdevelopers/hybrid-cloud-demo-backend
# set local lookup policy
oc set image-lookup hybrid-cloud-backend
oc import-image hybrid-cloud-frontend --confirm --all --from quay.io/rhdevelopers/hybrid-cloud-demo-frontend
# set local lookup policy
oc set image-lookup hybrid-cloud-frontend
----

[source,bash]
----
oc apply -k k8s/skupper/gcp
----

=== Cloud-2(aws)

=== Add Image Streams

[source,bash]
----
oc import-image hybrid-cloud-backend --confirm --all --from quay.io/rhdevelopers/hybrid-cloud-demo-backend
# set local lookup policy
oc set image-lookup hybrid-cloud-backend
----

[source,bash]
----
oc apply -k k8s/skupper/aws
----

=== Cloud-3(azr)

=== Add Image Streams

[source,bash]
----
oc import-image hybrid-cloud-backend --confirm --all --from quay.io/rhdevelopers/hybrid-cloud-demo-backend
# set local lookup policy
oc set image-lookup hybrid-cloud-backend
----

[source,bash]
----
oc apply -k k8s/skupper/azr
----

Run the following commands on *Cloud-1*, *Cloud-2* and *Cloud-3* to wait for skupper deployments to be ready:

[source,bash]
----
oc rollout status deployment skupper-site-controller
oc rollout status deployment skupper-router
oc rollout status deployment skupper-service-controller
----

== Backend Deployment

On all clouds *Cloud-1*, *Cloud-2* and *Cloud-3*, run the following commands to deploy `Knative` backend:

Deploy backend application(Knative):

[source,bash]
----
cd $BACKEND_APP_HOME
oc apply -k k8s/knative
----

[NOTE]
====
If you want traditional Kubenretes deployment then use the run the following command:
[source,bash]
----
cd $BACKEND_APP_HOME
oc apply -k k8s/vanilla
----
====

Run the following command to check the status:

[source,bash]
----
oc get pods,svc,ksvc
----

A successful deployments of `core`,`rbac`,`skupper` and `backend` components, should show an output like:

[source,text]
----
NAME                                                        READY   STATUS    RESTARTS   AGE
pod/hybrid-cloud-backend-p948k-deployment-b49c9569b-ggv8z   2/2     Running   0          26s
pod/skupper-router-56c4544bbc-dhckt                         3/3     Running   0          43m
pod/skupper-service-controller-5bcf486799-v2hl2             2/2     Running   0          43m
pod/skupper-site-controller-5cf967f858-z2dx8                1/1     Running   0          43m

NAME                                         TYPE           CLUSTER-IP       EXTERNAL-IP                                                  PORT(S)                             AGE
service/hybrid-cloud-backend                 ExternalName   <none>           kourier-internal.knative-serving-ingress.svc.cluster.local   <none>                              21s
service/hybrid-cloud-backend-p948k           ClusterIP      172.30.223.229   <none>                                                       80/TCP                              26s
service/hybrid-cloud-backend-p948k-private   ClusterIP      172.30.140.107   <none>                                                       80/TCP,9090/TCP,9091/TCP,8022/TCP   26s
service/hybrid-cloud-backend-skupper         LoadBalancer   172.30.1.23      <pending>                                                    80:31554/TCP                        29s
service/skupper-controller                   ClusterIP      172.30.119.15    <none>                                                       443/TCP                             43m
service/skupper-internal                     ClusterIP      172.30.205.136   <none>                                                       55671/TCP,45671/TCP                 43m
service/skupper-messaging                    ClusterIP      172.30.14.214    <none>                                                       5671/TCP                            43m
service/skupper-router-console               ClusterIP      172.30.72.116    <none>                                                       443/TCP                             43m

NAME                                               URL                                                                 LATESTCREATED                LATESTREADY                  READY   REASON
service.serving.knative.dev/hybrid-cloud-backend   http://hybrid-cloud-backend-hybrid-cloud-demo.apps.gcp.kameshs.me   hybrid-cloud-backend-p948k   hybrid-cloud-backend-p948k   True
----

[NOTE]
====
When using the vanilla deployment you will not have `ksvc` and `service/hybrid-cloud-backend-skupper` service.
====

== Connecting Clouds

=== Generate Skupper Connection Token

On *Cloud-1*, create the following Kubenretes Secret:

[source,bash]
----
skupper connection-token $HYBRID_CLOUD_HOME/token.yaml
----

The `token.yaml` will be used in other clouds *Cloud-2* and *Cloud-3* to connect the clouds using _Virtual Application Network(VAN)_. 


To connect *Cloud-2* and *Cloud-3* with *Cloud-1*, run the following command on *Cloud-2* and *Cloud-3*:

==== Cloud-2

Make sure the *Cloud-2* starts to spill over after *4* requests in queue:

[source,bash]
----
skupper connect --connection-name=cloud-1 --cost 4 $HYBRID_CLOUD_HOME/token.yaml
----

==== Cloud-3

Make sure the *Cloud-3* starts to spill over after *2* requests in queue:

[source,bash]
----
skupper connect --connection-name=cloud-1 --cost 2 $HYBRID_CLOUD_HOME/token.yaml
----

=== Verify Status

==== Cloud-1

Running `skupper status` on the clouds should show the following output:

[source,text]
----
Skupper is enabled for namespace '"hybrid-cloud-demo" in interior mode'. It is connected to 2 other sites. It has 1 exposed service.
----

==== Cloud-2

Running `skupper status` on the clouds should show the following output:

[source,text]
----
Skupper is enabled for namespace '"hybrid-cloud-demo" in interior mode'. It is connected to 2 other sites (1 indirectly). It has 1 exposed service.
----

==== Cloud-3

Running `skupper status` on the clouds should show the following output:

[source,text]
----
Skupper is enabled for namespace '"hybrid-cloud-demo" in interior mode'. It is connected to 2 other sites (1 indirectly). It has 1 exposed service.
----

[NOTE] 
====
Since *Cloud-1* is where we generated the `site-token` secret to connect to other sites, makes it directly connected to other clouds *Cloud-2* and *Cloud-3*. For other clouds you will see one direct to *Cloud-1* and one indirect connection to other cloud.
====

=== Verify Exposed Services

You can verify that, in all connected clouds running the following command `skupper list-exposed` shows the following output:

When `Knative` backend was deployed:

[source,bash]
----
Services exposed through Skupper:
    hybrid-cloud-backend-skupper (http port 80) with targets
      => hybrid-cloud-backend.hybrid-cloud-demo name=hybrid-cloud-backend.hybrid-cloud-demo
----

When standard Kubernetes (vanilla) backend was deployed:

[source,bash]
----
Services exposed through Skupper:
    hybrid-cloud-backend (http port 80) with targets
      => hybrid-cloud-backend.hybrid-cloud-demo name=hybrid-cloud-backend.hybrid-cloud-demo
----

== Frontend Deployment

On *Cloud-1* deploy the *frontend* by running the following command:

[source,bash]
----
cd $FRONTEND_APP_HOME
oc apply -k k8s/knative
----

Create OpenShift route to access the frontend application
[source,bash]
----
oc create route edge  --service=hybrid-cloud-frontend --port=8080
----
