apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hybrid-cloud
  labels:
    app.kubernetes.io/part-of: argocd
spec:
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: "*"
  description: Hybrid Cloud Demo
  destinations:
    - namespace: hybrid-cloud-demo
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: serving.knative.dev
      kind: "*"
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Namespace
    - group: tekton.dev
      kind: "*"
    - group: triggers.tekton.dev
      kind: "*"
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: rbac.authorization.k8s.io
      kind: "*"
    - group: ""
      kind: ServiceAccount
  orphanedResources:
    warn: false
  sourceRepos:
    - https://github.com/redhat-developer-demos/hybrid-cloud
    - https://github.com/redhat-developer-demos/hybrid-cloud-app-frontend
    - https://github.com/redhat-developer-demos/hybrid-cloud-app-backend
